window.CATALOG_PRODUCTS = [
  {
    id: 1,
    brand: "Nike",
    name: "Air Max 95",
    price: 180,
    color: "Black / Anthracite",
    description: "Una silueta urbana con amortiguación visible y una presencia marcada para el día a día.",
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop&auto=format",
    tag: "NUEVO",
  },
  {
    id: 2,
    brand: "Nike",
    name: "Air Force 1 Low",
    price: 120,
    color: "White / White",
    description: "El clásico de Nike que combina una base limpia con la comodidad de una leyenda.",
    img: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&h=800&fit=crop&auto=format",
    tag: "",
  },
  {
    id: 3,
    brand: "Jordan",
    name: "Air Jordan 1 Retro High",
    price: 210,
    color: "Chicago / White",
    description: "La silueta que cambió la cancha y la calle, con el carácter original de Jordan.",
    img: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=800&fit=crop&auto=format",
    tag: "SALE",
  },
  {
    id: 4,
    brand: "Jordan",
    name: "Air Jordan 4 Retro",
    price: 240,
    color: "Bred / Black",
    description: "Diseño estructurado, detalles icónicos y una actitud que se reconoce desde lejos.",
    img: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&h=800&fit=crop&auto=format",
    tag: "NUEVO",
  },
];